[package]
name = "cita-tool"
version = "0.19.0"
authors = ["piaoliu <441594700@qq.com>", "Qian Linfeng <thewawar@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "^0.12.1"
tokio = "^0.1.7"
futures = "^0.1"
serde_json = "^1.0.17"
serde = "^1.0.53"
serde_derive = "^1.0.53"
protobuf = "=2.8.1"
hex = "^0.3.2"
tiny-keccak = "^1.4.2"
secp256k1 = { version = "0.15.0", features = ["recovery"]}
blake2b_simd = "0.5.0"
ed25519-dalek = "0.9.1"
sha2 = "0.8.0"
libsm = "0.4.0"
# rename to types
types = { version = "^0.4.0", package = "ethereum-types"}
lazy_static = "^1.0"
rand = "^0.6.0"
uuid = { version = "0.7", features = ["serde", "v4"] }
failure = "^0.1.1"
ethabi = "^8.0"
tool-derive = { path = "../tool-derive" }
hyper-rustls = { version = "0.16.1", optional = true }
hyper-tls = { version = "^0.3", optional = true }

[features]
default = ["rustls"]
openssl = ["hyper-tls"]
rustls = ["hyper-rustls"]
